my_app/urls.py
from django.urls import path
from my_app import views

app_name ="my_app"

urlpatterns = [
  
    path('', views.index, name="index"),
    path('student_form/', views.student_form, name="student_form"),
    path('student_info/<int:student_id>/', views.student_info, name="student_info"),
    path('student_update/<int:student_id>/', views.student_update, name="student_update"),
    path('student_delete/<int:student_id>/', views.student_delete, name="student_delete"),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
]

my_app/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    first_name =models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email= models.EmailField()
    phone = models.IntegerField()


    def __str__(self):
        return str(self.pk)+" "+self.first_name+ " " + self.last_name    

my_app/forms.py
from django import forms
from my_app import models


class StudentForm(forms.ModelForm):
    class Meta:
        model = models.Student
        fields = "__all__"

my_app/views.py
from django.shortcuts import render
from my_app import forms
from my_app.models import Student


# Create your views here.

def index(request):
    student_list= Student.objects.order_by('first_name')
    diction= {'title': "index", 'student_list':student_list}
    return render(request,'my_app/index.html', context= diction)

def student_form(request):
    form = forms.StudentForm()

    if request.method == "POST":
        form = forms.StudentForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction= {'title': 'student Form', 'student_form': form}
    return render(request, 'my_app/student_form.html', context= diction)  


def student_info(request,student_id):
    student_info= Student.objects.get(pk=student_id)
    diction= {'student_info': student_info}
    return render(request,'my_app/student_info.html', context= diction) 


def student_update(request,student_id):
    student_info=Student.objects.get(pk=student_id)
    form = forms.StudentForm(instance=student_info)

    if request.method =='POST':
        form = forms.StudentForm(request.POST, instance=student_info)


        if form.is_valid():
            form.save(commit=True)
            return index(request)

    diction={'student_form': form}   
    return render(request,'my_app/student_update.html', context=diction)


def student_delete(request,student_id):
    student_info= Student.objects.get(pk=student_id).delete()
    diction= {'delete_message': "DELETE DONE"}
    return render(request,'my_app/student_delete.html', context= diction)     

templates/my_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title> {{title}} </title>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'my_app:index'%} ">Index</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'my_app:student_form' %}">Student Form </a>
        </li>
      </ul>

      {% block body_block %}

      {% endblock %}
    
</body>
</html>

templates/my_app/index.html
{% extends 'my_app/base.html' %}


{% block body_block %}

<h1> Student List </h1>
<ul>
{% if student_list %}

{% for student in student_list %}
<li> <a href="{% url 'my_app:student_info' student_id=student.id %}"> {{student.first_name}} {{student.last_name}}</a></li>
 {% endfor %}
{% else %}
  <h3> NO STUDENT </h3>
{% endif %}
</ul>
{% endblock %}

templates/my_app/student_delete.html
{% extends 'my_app/base.html' %}


{% block body_block %}

<div class="alert alert-danger"> {{delete_message}} </div>

{% endblock %}

templates/my_app/student_form.html
{% extends 'my_app/base.html' %}


{% block body_block %}

<h1> Student form </h1>
<form action="" method="POST">

    {{ student_form.as_p }}
    {% csrf_token %}

    <input type="submit" name="submit" value="Add Student">
</form>
{% endblock %}

templates/my_app/student_info.html
{% extends 'my_app/base.html' %}


{% block body_block %}
    <h1>Student info </h1>


<h3>Student Name : {{student_info.first_name}}{{student_info.last_name}}</h3>
<h3> Email : {{student_info.Email}}</h3>
<h3> phone: {{student_info.phone}}</h3>

<a href="{% url 'my_app:student_update' student_id=student_info.id %}" class="btn btn-primary">Update</a>
<a href="{% url 'my_app:student_delete' student_id=student_info.id %}" class="btn btn-primary">Delete</a>

{% endblock %}

templates/my_app/student_update.html
{% extends 'my_app/base.html' %}

{% block body_block %}

<h1> Student Update </h1>


<form action="" method="POST">

    {{student_form.as_p}}

    {% csrf_token %}

    <input type="submit" value="update">

</form>

{% endblock %}